### ISSUE TITLE
requests.exceptions.InvalidHeader: Invalid leading whitespace [...] '***\n\n'

### ISSUE THREAD

**Issue by behinger** [SimTech-Research-Data-Management/dataverse-sync#2]
I tried to use the action and got the following issue
```
Notice:  To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/runner/work/_actions/SimTech-Research-Data-Management/dataverse-sync/v1/repo_uploader.py", line 229, in <module>
    dataset_files = _get_file_list(
                    ^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/SimTech-Research-Data-Management/dataverse-sync/v1/repo_uploader.py", line 127, in _get_file_list
    response = requests.get(headers=headers, url=url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/requests/models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/requests/utils.py", line 1040, in check_header_validity
    _validate_header_part(header, value, 1)
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/requests/utils.py", line 1056, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: '***\n\n'
Error: Process completed with exit code 1.
```

my yaml: https://github.com/unfoldtoolbox/UnfoldSim.jl/blob/main/.github/workflows/darus-dataverse.yml

Thanks for your help!

**Comment by JR-1991** [comment]
Thanks @behinger for submitting the issue!

The issue might be caused by the value found in `persistent_id` since Dataverse relies on a specific DOI format. You can find the latter within your dataset's metadata. Here is an example of this repositories DOI:

<p align="center">
<img width="600" alt="image" src="https://github.com/SimTech-Research-Data-Management/dataverse-sync/assets/30547301/9528c674-4646-4cb8-93ce-70b6e4716fb6">
</p>

Can you retry it with the following line in your workflow?

```yaml
persistent_id: "doi:10.18419/darus-3804"
```

**Comment by behinger** [comment]
I see - I copied it from darus but from some other place probably.

maybe modifying the readme example could clarify this :)

- but alas, it didnt help. same error

**Comment by JR-1991** [comment]
I just added it to the `README` for clarification 🙌

Alright, it seems like something is wrong with the header that could originate from your API-Token. I am going to clone your repository and try it by myself on another private dataset if that is fine for you?

**Comment by behinger** [comment]
sure!
![grafik](https://github.com/SimTech-Research-Data-Management/dataverse-sync/assets/10183650/5a3b0c16-9723-4c98-9b83-6e8212227c49)

this is what I did, and then copied in the API key directly without any bells and whistles

**Comment by behinger** [comment]
ok - my bad somehow no API key.
now I run into
```
 Traceback (most recent call last):
  File "/home/runner/work/_actions/SimTech-Research-Data-Management/dataverse-sync/v1/repo_uploader.py", line 250, in <module>
    files = [_to_file_object(file, SUBDIR) for file in repo_files + [".dvregistry"]]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/SimTech-Research-Data-Management/dataverse-sync/v1/repo_uploader.py", line 250, in <listcomp>
    files = [_to_file_object(file, SUBDIR) for file in repo_files + [".dvregistry"]]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/SimTech-Research-Data-Management/dataverse-sync/v1/repo_uploader.py", line 62, in _to_file_object
    return File(
           ^^^^^
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for File
checksum
  Filepath scripts is not a file. (type=type_error)
Error: Process completed with exit code 1.
```

**Comment by JR-1991** [comment]
I was able to resolve the issue on my side. The `file_list` was created with directories inside, which causes the latter error. Can you target this action's `main` branch within your workflow and re-add your API Token secret to be sure? If it works, I will publish a new release to hot-fix this.

```yaml
name: DARUS dataverse sync

on: [push]

jobs:
  dv-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Synchronize to DV
      uses: SimTech-Research-Data-Management/dataverse-sync@main
      with:
        dataverse_url: "https://darus.uni-stuttgart.de/"
        api_token: ${{ secrets.DV_API_TOKEN }}
        persistent_id: "doi:10.18419/darus-3804"
```

![image](https://github.com/SimTech-Research-Data-Management/dataverse-sync/assets/30547301/e32e2e3f-376f-438c-a425-fe24c558d77f)

**Comment by behinger** [comment]
works now on @main!
